.CODE

.DATA	0: a: 8: b: 16: c: 
.CODE
0: PUSHW 8 PUSHW 8 GETSL PUSHW 3 PUSHW 0 GETSW MULI CVTIF ADDF 
	PUTSL 
/* Begin loop */
18: 
.DATA	24: p: 32: d: 
.CODE
/* Begin if */
18: PUSHW 0 GETSW PUSHW 8 GETSL CVTIF SWAPW PUSHW 0 GETSW PUSHW 8 
	GETSL SUBI TSTLTI 38: PUSHW 16 PUSHW 3 PUSHW 24 GETSL CVTIF MULF PUSHW 32 GETSW 
	PUSHW 4 DIVF CVTIF CVTIF PUSHW 3 PUSHW 24 GETSL CVTIF MULF PUSHW 32 
	GETSW PUSHW 4 DIVF CVTIF SUBI TSTLTI NOTW PUTSW 
/* End of if */
82: 
/* Else */

.DATA	16: c: 
.CODE
82: PUSHW 8 PUSHW 24 GETSL PUSHW 16 GETSW CVTIF SUBF PUSHW 17 
	PUSHW 0 GETSW DIVF CVTIF CVTIF ADDF PUTSL 
/* End Else */
107: /* End of loop */
107: HALT  .ENTRY 0
