/* The following code was generated by JFlex 1.4.3 on 11/4/17 8:25 PM */

import java.io.*;
import java.util.Scanner;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/4/17 8:25 PM from the specification file
 * <tt>proj1.l</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\3\25\0\1\6\7\0\1\47\1\50\1\45\1\43"+
    "\1\37\1\44\1\4\1\46\12\2\1\36\1\35\1\41\1\40\1\42"+
    "\2\0\2\1\1\5\27\1\4\0\1\34\1\0\1\17\1\22\1\24"+
    "\1\15\1\13\1\10\1\26\1\12\1\7\2\1\1\21\1\33\1\14"+
    "\1\23\1\27\1\1\1\20\1\25\1\11\1\32\1\16\1\31\1\30"+
    "\2\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\16\2"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\5\1\0\1\23\2\2"+
    "\1\24\15\2\1\25\3\2\1\26\1\27\1\30\1\6"+
    "\1\31\1\32\1\2\1\33\2\2\1\34\1\35\1\36"+
    "\1\37\7\2\1\40\1\2\1\41\1\42\1\2\1\43"+
    "\1\44\1\45\1\2\1\46\1\2\1\47\1\50\2\2"+
    "\1\51\1\52\2\2\1\53\1\2\1\54\1\55\1\2"+
    "\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\122\0\122\0\315"+
    "\0\366\0\u011f\0\u0148\0\u0171\0\u019a\0\u01c3\0\u01ec\0\u0215"+
    "\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2\0\u030b\0\122\0\u0334"+
    "\0\122\0\122\0\u035d\0\u0386\0\122\0\122\0\122\0\122"+
    "\0\122\0\122\0\u03af\0\u03d8\0\173\0\u0401\0\u042a\0\173"+
    "\0\u0453\0\u047c\0\u04a5\0\u04ce\0\u04f7\0\u0520\0\u0549\0\u0572"+
    "\0\u059b\0\u05c4\0\u05ed\0\u0616\0\u063f\0\173\0\u0668\0\u0691"+
    "\0\u06ba\0\122\0\122\0\122\0\u06e3\0\u070c\0\173\0\u0735"+
    "\0\173\0\u075e\0\u0787\0\u07b0\0\173\0\173\0\173\0\u07d9"+
    "\0\u0802\0\u082b\0\u0854\0\u087d\0\u08a6\0\u08cf\0\173\0\u08f8"+
    "\0\173\0\173\0\u0921\0\173\0\173\0\122\0\u094a\0\173"+
    "\0\u0973\0\173\0\173\0\u099c\0\u09c5\0\173\0\173\0\u09ee"+
    "\0\u0a17\0\173\0\u0a40\0\173\0\173\0\u0a69\0\173";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\4\1\10\1\11"+
    "\1\4\1\12\1\4\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\3\4\1\24\1\4\1\25"+
    "\1\4\1\26\1\3\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\3"+
    "\1\4\1\5\1\6\1\43\1\4\1\10\1\11\1\4"+
    "\1\12\1\4\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\3\4\1\24\1\4\1\25\1\4"+
    "\1\26\1\3\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\52\0\2\4"+
    "\2\0\1\4\1\0\26\4\16\0\1\5\1\0\1\44"+
    "\52\0\1\10\43\0\2\4\2\0\1\4\1\0\1\4"+
    "\1\45\3\4\1\46\20\4\15\0\2\4\2\0\1\4"+
    "\1\0\3\4\1\47\10\4\1\50\11\4\15\0\2\4"+
    "\2\0\1\4\1\0\5\4\1\51\4\4\1\52\6\4"+
    "\1\53\4\4\15\0\2\4\2\0\1\4\1\0\14\4"+
    "\1\54\11\4\15\0\2\4\2\0\1\4\1\0\1\55"+
    "\25\4\15\0\2\4\2\0\1\4\1\0\10\4\1\56"+
    "\15\4\15\0\2\4\2\0\1\4\1\0\5\4\1\57"+
    "\10\4\1\60\7\4\15\0\2\4\2\0\1\4\1\0"+
    "\4\4\1\61\21\4\15\0\2\4\2\0\1\4\1\0"+
    "\14\4\1\62\11\4\15\0\2\4\2\0\1\4\1\0"+
    "\1\63\3\4\1\64\7\4\1\65\11\4\15\0\2\4"+
    "\2\0\1\4\1\0\11\4\1\66\14\4\15\0\2\4"+
    "\2\0\1\4\1\0\23\4\1\67\2\4\15\0\2\4"+
    "\2\0\1\4\1\0\3\4\1\70\22\4\15\0\2\4"+
    "\2\0\1\4\1\0\14\4\1\71\11\4\54\0\1\72"+
    "\50\0\1\73\50\0\1\74\15\0\1\75\45\0\1\76"+
    "\1\0\1\44\45\0\2\4\2\0\1\4\1\0\2\4"+
    "\1\77\23\4\15\0\2\4\2\0\1\4\1\0\4\4"+
    "\1\100\21\4\15\0\2\4\2\0\1\4\1\0\6\4"+
    "\1\101\17\4\15\0\2\4\2\0\1\4\1\0\16\4"+
    "\1\102\7\4\15\0\2\4\2\0\1\4\1\0\1\103"+
    "\25\4\15\0\2\4\2\0\1\4\1\0\2\4\1\104"+
    "\23\4\15\0\2\4\2\0\1\4\1\0\7\4\1\105"+
    "\16\4\15\0\2\4\2\0\1\4\1\0\11\4\1\106"+
    "\14\4\15\0\2\4\2\0\1\4\1\0\6\4\1\107"+
    "\17\4\15\0\2\4\2\0\1\4\1\0\16\4\1\110"+
    "\7\4\15\0\2\4\2\0\1\4\1\0\10\4\1\111"+
    "\4\4\1\112\10\4\15\0\2\4\2\0\1\4\1\0"+
    "\14\4\1\113\11\4\15\0\2\4\2\0\1\4\1\0"+
    "\5\4\1\114\20\4\15\0\2\4\2\0\1\4\1\0"+
    "\17\4\1\115\6\4\15\0\2\4\2\0\1\4\1\0"+
    "\14\4\1\116\11\4\15\0\2\4\2\0\1\4\1\0"+
    "\2\4\1\117\23\4\15\0\2\4\2\0\1\4\1\0"+
    "\4\4\1\120\21\4\15\0\2\4\2\0\1\4\1\0"+
    "\6\4\1\121\17\4\14\0\3\75\1\0\45\75\2\0"+
    "\1\76\47\0\2\4\2\0\1\4\1\0\5\4\1\122"+
    "\20\4\15\0\2\4\2\0\1\4\1\0\1\123\3\4"+
    "\1\124\21\4\15\0\2\4\2\0\1\4\1\0\2\4"+
    "\1\125\23\4\15\0\2\4\2\0\1\4\1\0\26\4"+
    "\3\0\1\126\11\0\2\4\2\0\1\4\1\0\4\4"+
    "\1\127\21\4\15\0\2\4\2\0\1\4\1\0\12\4"+
    "\1\130\13\4\15\0\2\4\2\0\1\4\1\0\14\4"+
    "\1\131\11\4\15\0\2\4\2\0\1\4\1\0\20\4"+
    "\1\132\5\4\15\0\2\4\2\0\1\4\1\0\6\4"+
    "\1\133\17\4\15\0\2\4\2\0\1\4\1\0\1\134"+
    "\25\4\15\0\2\4\2\0\1\4\1\0\12\4\1\135"+
    "\13\4\15\0\2\4\2\0\1\4\1\0\5\4\1\136"+
    "\20\4\15\0\2\4\2\0\1\4\1\0\1\4\1\137"+
    "\24\4\15\0\2\4\2\0\1\4\1\0\11\4\1\140"+
    "\14\4\15\0\2\4\2\0\1\4\1\0\11\4\1\141"+
    "\14\4\15\0\2\4\2\0\1\4\1\0\5\4\1\142"+
    "\20\4\15\0\2\4\2\0\1\4\1\0\4\4\1\143"+
    "\21\4\15\0\2\4\2\0\1\4\1\0\2\4\1\144"+
    "\23\4\15\0\2\4\2\0\1\4\1\0\6\4\1\145"+
    "\17\4\15\0\2\4\2\0\1\4\1\0\10\4\1\146"+
    "\15\4\15\0\2\4\2\0\1\4\1\0\5\4\1\147"+
    "\20\4\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2706];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\2\11\17\1\1\11\1\1\2\11"+
    "\2\1\6\11\1\1\1\0\25\1\3\11\31\1\1\11"+
    "\21\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
private Parser parser;
private PrintWriter outFile;
public Yylex (java.io.Reader inFile, Parser parser)
{
	this (inFile);
	this.parser = parser;
	this.outFile = outFile;
}
private int line = 0;

void yyerror (String s)
{
	System.err.println (s);
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 104) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 32: 
          { return parser.Put;
          }
        case 47: break;
        case 34: 
          { return parser.Then;
          }
        case 48: break;
        case 44: 
          { return parser.Assert;
          }
        case 49: break;
        case 35: 
          { return parser.Else;
          }
        case 50: break;
        case 24: 
          { return parser.Ge;
          }
        case 51: break;
        case 1: 
          { yyerror ("Bad Character");
          }
        case 52: break;
        case 4: 
          { line++;
          }
        case 53: break;
        case 41: 
          { return parser.When;
          }
        case 54: break;
        case 12: 
          { return parser.Gt;
          }
        case 55: break;
        case 39: 
          { return parser.Loop;
          }
        case 56: break;
        case 36: 
          { return parser.Exit;
          }
        case 57: break;
        case 13: 
          { return parser.Plus;
          }
        case 58: break;
        case 43: 
          { return parser.Begin;
          }
        case 59: break;
        case 37: 
          { return parser.Ne;
          }
        case 60: break;
        case 46: 
          { return parser.Boolean;
          }
        case 61: break;
        case 9: 
          { return parser.Comma;
          }
        case 62: break;
        case 6: 
          { ;
          }
        case 63: break;
        case 20: 
          { return parser.To;
          }
        case 64: break;
        case 15: 
          { return parser.Star;
          }
        case 65: break;
        case 30: 
          { return parser.Var;
          }
        case 66: break;
        case 26: 
          { return parser.Integer;
          }
        case 67: break;
        case 3: 
          { return parser.IntConst;
          }
        case 68: break;
        case 8: 
          { return parser.Colon;
          }
        case 69: break;
        case 22: 
          { return parser.Eq;
          }
        case 70: break;
        case 42: 
          { return parser.Elsif;
          }
        case 71: break;
        case 38: 
          { return parser.Real;
          }
        case 72: break;
        case 16: 
          { return parser.Slash;
          }
        case 73: break;
        case 27: 
          { return parser.End;
          }
        case 74: break;
        case 23: 
          { return parser.Le;
          }
        case 75: break;
        case 19: 
          { return parser.If;
          }
        case 76: break;
        case 40: 
          { return parser.Bind;
          }
        case 77: break;
        case 45: 
          { return parser.Record;
          }
        case 78: break;
        case 11: 
          { return parser.Lt;
          }
        case 79: break;
        case 33: 
          { return parser.Mod;
          }
        case 80: break;
        case 14: 
          { return parser.Minus;
          }
        case 81: break;
        case 5: 
          { return parser.Dot;
          }
        case 82: break;
        case 17: 
          { return parser.LParen;
          }
        case 83: break;
        case 7: 
          { return parser.Semi;
          }
        case 84: break;
        case 29: 
          { return parser.Div;
          }
        case 85: break;
        case 18: 
          { return parser.RParen;
          }
        case 86: break;
        case 2: 
          { return parser.Ident;
          }
        case 87: break;
        case 25: 
          { return parser.RealConst;
          }
        case 88: break;
        case 31: 
          { return parser.And;
          }
        case 89: break;
        case 28: 
          { return parser.Not;
          }
        case 90: break;
        case 21: 
          { return parser.Or;
          }
        case 91: break;
        case 10: 
          { return parser.Assign;
          }
        case 92: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
